# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release Code on Flask app stage

on:
  push:
    tags:
      - v1.1.1

jobs:
  release-build:
    runs-on: prod

    steps:
      - uses: actions/checkout@v4

      - name: Copy Code in /app dir
        run: |
          sudo mkdir -p /app
          sudo cp -rvf $GITHUB_WORKSPACE/. /app

      - name: Install Requirements
        working-directory: /app
        run: | 
          sudo pip3.12 install -r requirements.txt --break-system-packages

      - name: start flaskapp 
        run: | 
          sudo systemctl restart flask-app.service    
